### ISSUE TITLE
Is it possible to use with AMD GPUs?

### ISSUE THREAD

**Issue by Extarys** [rjmacarthy/twinny-api#9]
Is it possible to adapt/use this with an AMD GPU? I'm not sure on the technical side of things how this works/could work with AMD.

(This project looks awesome, hope I'll be able to try it one day)

**Comment by rjmacarthy** [comment]
Hey, appreciate your interest in the project.  About running it on AMD GPUs, honestly, I'm not too sure since I've only used NVIDIA. Maybe you could try running the API with python directly without Docker and see how it goes, the libraries I used to run the models are from huggingface so they might have some information about it.
